#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "Too few arguments"
    exit 22
fi

classpath="$1"
mainclass="$2"
shift 2
exec /system/bin/app_process -Djava.class.path="$classpath" "$(pwd)" "$mainclass" "$@"