// NOTICE: The types code is generated by AI.
// They might not be accurate or complete.
// Please verify the types carefully

declare class ZIndexManagerClass {
    #elements: HTMLElement[];
    #zIndexBase: number;
    #zIndexMax: number;
    #updateQueued: boolean;

    get [Symbol.toStringTag](): string;

    /** Get the currently active (topmost) element. */
    get activeElement(): HTMLElement | null;

    constructor();

    /**
     * Configure the z-index range.
     * @param zIndexBase - Base z-index value (must be >= 1).
     * @param zIndexMax - Maximum z-index value (must be >= zIndexBase).
     * @throws {TypeError} If zIndexBase or zIndexMax is invalid.
     */
    config(zIndexBase: number, zIndexMax: number): void;

    /** Add an element to the manager. */
    add(element: HTMLElement): void;

    /** Remove an element from the manager. */
    remove(element: HTMLElement): void;

    /** Force an update of all z-index values (debounced via requestAnimationFrame). */
    update(): void;

    /** Activate an element (bring to top). */
    activate(element: HTMLElement): void;

    /** Deactivate an element (send to bottom). */
    deactivate(element: HTMLElement): void;

    /** Internal method to update z-index values. */
    #update(): void;
}

export { ZIndexManagerClass };